const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const ImageSchema = new Schema({
    id:{
        type:String,
        required:true
    },
    created_at_host:{
        type: Date,
        required:true,
        default:"null"
    },
    width:{
        type:Number,
        required:true
    },
    height:{
        type:Number,
        required:true
    },
    orientation:{
        type:String,
        required:true
    },
    color:{
        type:String,
        required:true,
        default:"null"
    },
    blur_hash:{
        type:String,
        required:true,
        default:"null"
    },
    description:{
        type:String,
        required:false,
        default:"null"
    },
    alt_description:{
        type:String,
        required:false,
        default:"null"
    },
    ai_description1:{
        type:String,
        default:"null"
    },
    ai_description2:{
        type:String,
        default:"null"
    },
    tags:{
        type:Array,
        required:true,
        default:["null"]
    },
    urls_raw:{
        type:String,
        required:true,
    },
    urls_full:{
        type:String,
        required:true,
    },
    urls_regular:{
        type:String,
        required:true,
    },
    urls_small:{
        type:String,
        required:true,
    },
    urls_thumb:{
        type:String,
        required:true,
    },
    links_html:{
        type:String,
        required:true,
    },
    links_download:{
        type:String,
        required:true,
    },
    user_id:{
        type:String,
        required:true,
    },
    user_username:{
        type:String,
        required:true,
    },
    user_name:{
        type:String,
        required:true,
    },
    user_first_name:{
        type:String,
        required:true,
    },
    user_last_name:{
        type:String,
        required:false,
        default:"null"
    },
    user_twitter_username:{
        type:String,
        required:false,
        default:"null"
    },
    user_instagram_username:{
        type:String,
        required:false,
        default:"null"
    },
    user_portfolio_url:{
        type:String,
        required:false,
        default:"null"
    },
    user_bio:{
        type:String,
        required:false,
        default:"null"
    },
    user_profile_image_small:{
        type:String,
        required:true,
        default:"null",
    },
    user_profile_image_medium:{
        type:String,
        required:true,
        default:"null",
    },
    user_profile_image_large:{
        type:String,
        required:true,
        default:"null",
    },
    user_profile_image_raw:{
        type:String,
        required:true,
        default:"null",
    },
    update_count:{
        type:Number,
        required:true
        // default:0
    },
    created_at:{
        type:Date,
        required:true,
        default:Date.now,
    },
    updated_at:{
        type:Date,
        required:true,
        default:Date.now,
    }   
});

module.exports = mongoose.model('image', ImageSchema );
// module.exports = {Image: mongoose.model('image', ImageSchema )};
